routes/web.php
<?php

use App\Library\ElasticMail;
use App\Models\ScheduledEcard;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {

    return view('welcome');
 })->name('home');

 Route::get('/login', function () {

    return view('adminlte::auth.login');
 })->name('home');
Route::get('/payment/{id}', function ($id) {
   return view('payment',compact('id'));
});

Route::get('payment-status','Payment\PaymentController@status')->name('status');



Route::group(['prefix'=>'admin','namespace'=>'Admin'],function (){
    //Auth Routes For Admin
    Route::get('login','Auth\LoginController@showLoginForm')->name('admin.showLogin');
    Route::post('login','Auth\LoginController@login')->name('admin.login');
    Route::group(['middleware' =>'admin'],function(){
        Route::get('logout', 'Auth\LoginController@logout')->name('admin.logout');
        Route::get('/','DashboardController@index')->name('admin.index');
        Route::resource('users', 'UsersController');
        Route::resource('categories', 'CategoriesController');
        Route::resource('subcategories', 'SubCategoriesController');
        Route::resource('products', 'ProductsController');


    });
});

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    //Relations
    public function subcategories()
    {
        return $this->hasMany(SubCategory::class,'category_id');
    }
}

app/Http/Controllers/Admin/CategoriesController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Category;
use Illuminate\Http\Request;

class CategoriesController extends Controller
{
    protected $model = Category::class;
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        return view('admin.categories.index',['categories' => $this->model::all()]);

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/admin/categories/index.blade.php
@extends('admin.layouts.master')
@section('title','الاقسام الرئيسية')
@push('styles')
    <link href="{{asset('assets/plugins/custom/datatables/datatables.bundle.css')}}" rel="stylesheet" type="text/css" />
@endpush

@section('content')

    <div class="kt-portlet kt-portlet--mobile">
        <div class="kt-portlet__head kt-portlet__head--lg">
            <div class="kt-portlet__head-label">
                <span class="kt-portlet__head-icon">
                    <i class="kt-font-brand flaticon2-line-chart"></i>
                </span>
                <h3 class="kt-portlet__head-title">
                    الاقسام الرئيسية
                </h3>
            </div>
            <div class="kt-portlet__head-toolbar">
                <div class="kt-portlet__head-wrapper">
                    <div class="kt-portlet__head-actions">
                        <a href="#" class="btn btn-brand btn-elevate btn-icon-sm" data-toggle="modal" data-target="#add_category">
                            <i class="la la-plus"></i>
                            إضافة قسم
                        </a>
                    </div>
                </div>
            </div>
            <div class="modal fade show" id="add_category" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"  aria-modal="true">
                <div class="modal-dialog" role="document">
                    <form class="kt-form">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title" id="exampleModalLabel">اضافة قسم</h5>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                </button>
                            </div>
                            <div class="modal-body">
                                <div class="form-group">
                                    <label>اسم القسم</label>
                                    <input type="email" class="form-control" aria-describedby="emailHelp" placeholder="اسم القسم">
                                </div>
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-primary">حفظ</button>
                                <button type="button" class="btn btn-secondary" data-dismiss="modal">الغاء</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>

        <div class="kt-portlet__body">

            <!--begin: Datatable -->
            <table class="table table-striped- table-bordered table-hover table-checkable" id="kt_table_3">
                <thead>
                <tr>
                    <th>رقم تسلسلي</th>
                    <th>الاسم</th>
                    <th>اجراءات</th>
                </tr>
                </thead>
                <tbody>
                @foreach($categories as $catgory)
                    <tr>
                        <td>{{$catgory->id}}</td>
                        <td>{{$catgory->name}}</td>
                        <td>
                            <div class="row">
                                <div class="col-md-4">
                                    <a href="{{route('categories.edit',$catgory->id)}}" class="btn btn-sm btn-clean btn-icon btn-icon-md" title="View">
                                        <i class="la la-edit"></i>
                                    </a>
                                </div>
                                <div class="col-md-4">
                                    <div class="col-md-6">
                                        <form action="{{route('categories.destroy',$catgory->id)}}" method="POST">
                                            {{ csrf_field() }}
                                            <input type="hidden" name="_method" value="delete">
                                            <button type="submit" class="btn btn-sm btn-clean btn-icon btn-icon-md" title="Delete"><i class="la la-remove"></i></button>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>

            <!--end: Datatable -->
        </div>
    </div>

@endsection

@push('scripts')
    <!--begin::Page Vendors(used by this page) -->
    <script src="{{asset('assets/plugins/custom/datatables/datatables.bundle.js')}}" type="text/javascript"></script>

    <!--end::Page Vendors -->

    <!--begin::Page Scripts(used by this page) -->
    <script src="{{asset('assets/js/pages/crud/datatables/data-sources/html.js')}}" type="text/javascript"></script>

    <!--end::Page Scripts -->

@endpush